Gma ohirs
jswhit/build_gsinfo pull request #10
Opened 2022-09-13 21:04 UTC by jswhit

HIRS channel selection is different (2-15 for NOAA, NASA does not use 9 or 13-15)

2022-09-23 16:44 UTC, frolovsa requested changes
Thank you Jeff for combing through this. Looks like you found a couple of bugs that Sherrie missed (e.g. n14). 

I have on note, see comments inline.

2022-09-23 16:44 UTC, frolovsa commented on satinfo/hirs4_n19/readme
> +n19  20091215 000000  20130705 140000  hirs4 14    2 3 4 5 6 7 8 9 10 11 12 13 14 15
do we want to start on 20090414 like nasa

2022-09-27 19:34 UTC, jswhit commented on satinfo/hirs4_n19/readme
> +n19  20091215 000000  20130705 140000  hirs4 14    2 3 4 5 6 7 8 9 10 11 12 13 14 15
NASA didn't, the note says that maybe they should since the data should be available.  When do we start having hirs4_n19 data?

2022-09-27 19:35 UTC, jswhit commented
> 

I've been putting notes on differences in channel selection in the issue (https://github.com/jswhit/build_gsinfo/issues/6)

2022-09-27 22:14 UTC, frolovsa commented on satinfo/hirs4_n19/readme
> +n19  20091215 000000  20130705 140000  hirs4 14    2 3 4 5 6 7 8 9 10 11 12 13 14 15
i will check.

2022-10-17 19:17 UTC, merged